ubuntu@controller:~/apache2$ cat apache2.yml
---
- hosts: node1.example.com
  become: yes
  vars:
    src_path: /home/ubuntu/apache2
    dst_path: /var/www/html
  tasks:
  - name: Install apache2 package
    package: name={{ item }} update_cache=yes state=latest
    loop:
      - apache3
      - vim
      - screen
    tags: [ 'setup' ]
    ignore_errors: yes

  - name: Copy Index Page
    copy:
     src: "{{src_path}}/index.html"
     dest: "{{dst_path}}/index.html"
     owner: root
     group: root
     mode: '0644'
    tags: [ 'update', 'sync' ]


  - name: Start the services
    service: name=apache2 state=started enabled=yes
    tags: [ 'service' ]

  - name: Changing Port number
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen 80
    notify: Restart apache2
    tags: [ 'change', 'sync']

  handlers:
  - name: Restart apache2
    service: name=apache2 state=restarted


...
